import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul className="w-screen h-10 bg-black text-white flex justify-evenly items-center *:cursor-pointer">
          <li>dashboard</li>
          <li>products</li>
        </ul>
        {children}
      </body>
    </html>
  );
}
